### ISSUE TITLE
TLS certificates

### ISSUE THREAD

**Issue by aairey** [fstab/docker-weechat-otr#1]
Hello,

I use WeeChat to connect to the IRC gateway of Slack.

But unfortunately the SSL certificate is not trusted.  
I believe the `ca-certificates` of the Docker image need updating?

```
08:11:00 slackteamXX  ℹ  ╡ gnutls: connected using 2048-bit Diffie-Hellman shared secret exchange
08:11:00 slackteamXX  ℹ  ╡ gnutls: receiving 2 certificates
08:11:00 slackteamXX  ℹ  ╡  - certificate[1] info:
08:11:00 slackteamXX  ℹ  ╡    - subject `C=US,ST=California,L=San Francisco,O=Tiny Speck,CN=*.irc.slack.com', issuer `C=US,O=GeoTrust Inc.,CN=GeoTrust SSL CA - G3', RSA key 2048 bits, signed
                         ╡ using RSA-SHA256, activated `2015-11-25 00:00:00 UTC', expires `2017-12-02 23:59:59 UTC', SHA-1 fingerprint `ed4dcb04c89dc80d43e65437e7c4632dcf50ac86'
08:11:00 slackteamXX  ℹ  ╡  - certificate[2] info:
08:11:00 slackteamXX  ℹ  ╡    - subject `C=US,O=GeoTrust Inc.,CN=GeoTrust SSL CA - G3', issuer `C=US,O=GeoTrust Inc.,CN=GeoTrust Global CA', RSA key 2048 bits, signed using RSA-SHA256,
                         ╡ activated `2013-11-05 21:36:50 UTC', expires `2022-05-20 21:36:50 UTC', SHA-1 fingerprint `5aeaee3f7f2a9449cebafeec68fdd184f20124a7'
08:11:00 slackteamXX   ⚠ ╡ gnutls: peer's certificate is NOT trusted
08:11:00 slackteamXX   ⚠ ╡ gnutls: peer's certificate issuer is unknown
08:11:00 slackteamXX   ⚠ ╡ irc: TLS handshake failed
08:11:00 slackteamXX   ⚠ ╡ irc: error: Error in the certificate.
```

**Comment by fstab** [comment]
Hi, the last update of the image was 10 months ago, so it could well be some certificates are outdated. I updated the image. Please try again. I didn't look into the error, so if the update didn't help please comment again.

**Comment by aairey** [comment]
Hello, thanks for your quick reply and update of the image!

It was not working but with furhter troubleshooting I found that my CA path was wrong.
I had `gnutls_ca_file = "/etc/pki/tls/certs/ca-bundle.crt"` in my weechat.conf.

I found out the image has the file `/etc/ssl/certs/ca-certificates.crt` in stead, so I changed it and it is working fine now.
