### ISSUE TITLE
Additional python libraries

### ISSUE THREAD

**Issue by aairey** [fstab/docker-weechat-otr#2]
For running custom weechat scripts, it would be nice to have some basic libraries available like:
 `python-requests`

If this is out of scope for this image, no worries but I will have to create my own :)

**Comment by fstab** [comment]
There are a lot of python libraries available, which ones do you think would make a nice set of basic libraries for the Docker image? Only `python-requests` or more? If there are not too many, it should be a good idea to add them.

**Comment by aairey** [comment]
I don't know, but a lot is included as standard libraries in Python.

If I look at the [scripts](https://weechat.org/scripts/) available, not many extra libraries should be needed actually.
Maybe just `requests`, `feedparser`, `json` and `websocket` would cover a lot of use cases.
Just search for 'requires' on that page.

edit: Maybe `python-dbus` can also be [interesting](https://github.com/thefinn93/signal-weechat), although the use-case within docker might be limited.
edit: It seems `json` and `feedparser` are already present.

**Comment by aairey** [comment]
In addition `yowsup` could be interesting for the whatsapp.py WeeChat plugin.

Could you check if this is feasible?
If you don't have the time I might play around with it myself.
